# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetARock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps', '7.3.0'
  pod 'Google-Maps-iOS-Utils', '~> 4.1.0'

  # Pods for GetARock

  target 'GetARockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetARockUITests' do
    # Pods for testing
  end

end
